# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UItest2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Foto1 = QtWidgets.QLabel(self.centralwidget)
        self.Foto1.setGeometry(QtCore.QRect(190, 70, 511, 371))
        self.Foto1.setText("")
        self.Foto1.setPixmap(QtGui.QPixmap("C:/Users/tomas/Desktop/Coding/Ferrari.jpg"))
        self.Foto1.setScaledContents(True)
        self.Foto1.setObjectName("Foto1")
        self.FerrariButton = QtWidgets.QPushButton(self.centralwidget)
        self.FerrariButton.setGeometry(QtCore.QRect(210, 540, 141, 61))
        self.FerrariButton.setObjectName("FerrariButton")
        self.SpaceXbutton = QtWidgets.QPushButton(self.centralwidget)
        self.SpaceXbutton.setGeometry(QtCore.QRect(560, 540, 151, 61))
        self.SpaceXbutton.setObjectName("SpaceXbutton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.FerrariButton.clicked.connect(self.show_ferrari)
        self.SpaceXbutton.clicked.connect(self.show_spaceX)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FerrariButton.setText(_translate("MainWindow", "Ferrari"))
        self.SpaceXbutton.setText(_translate("MainWindow", "Space X"))

    def show_ferrari(self):
        self.Foto1.setPixmap(QtGui.QPixmap("C:/Users/tomas/Desktop/Coding/Ferrari.jpg"))

    def show_spaceX(self):
        self.Foto1.setPixmap(QtGui.QPixmap("C:/Users/tomas/Desktop/Coding/spaceX.jpg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
