# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UItest2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(927, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_x = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_x.setGeometry(QtCore.QRect(70, 170, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.comboBox_x.setFont(font)
        self.comboBox_x.setObjectName("comboBox_x")
        self.comboBox_x.addItem("")
        self.comboBox_x.addItem("")
        self.comboBox_y = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_y.setGeometry(QtCore.QRect(540, 170, 321, 141))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.comboBox_y.setFont(font)
        self.comboBox_y.setObjectName("comboBox_y")
        self.comboBox_y.addItem("")
        self.comboBox_y.addItem("")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(220, 380, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(320, 540, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 100, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 100, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 927, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.submit_button.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox_x.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_x.setItemText(1, _translate("MainWindow", "1"))
        self.comboBox_y.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_y.setItemText(1, _translate("MainWindow", "1"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.result_label.setText(_translate("MainWindow", "X XOR Y ="))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))

    def pressed(self):
        x = int(self.comboBox_x.currentText())
        y = int(self.comboBox_y.currentText())

        xor = (x and not y) or (not x and y)

        self.result_label.setText("X XOR Y =" + " " + str(xor))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
